// Paste this into the DevTools console on https://baileysnyder.com/jconj/
// It fetches the site's own JS bundle, regex-extracts every
// {kanji:"...",type:"...",eng:"..."} vocabulary entry, strips furigana
// from the kanji field to get the base form, and prints a ready-to-paste
// `WORD_CLASS` object for src/words.js.
//
// Site types map to our class codes 1:1 (u, ru, irv, ira, i, na).

(async () => {
  const scriptEl = document.querySelector('script[src*="index."]');
  if (!scriptEl) {
    console.error('Could not find the site bundle <script> tag.');
    return;
  }
  const src = new URL(scriptEl.src, location.href).toString();
  const text = await (await fetch(src)).text();

  const re = /\{kanji:"((?:[^"\\]|\\.)*)",type:"(\w+)",eng:"((?:[^"\\]|\\.)*)"\}/g;
  const stripFurigana = (kanjiHtml) => {
    const div = document.createElement('div');
    div.innerHTML = kanjiHtml;
    div.querySelectorAll('rt').forEach((rt) => rt.remove());
    return div.textContent;
  };

  const entries = [];
  const seen = new Map();
  let m;
  while ((m = re.exec(text)) !== null) {
    const base = stripFurigana(m[1]);
    const type = m[2];
    if (seen.has(base) && seen.get(base) !== type) {
      console.warn(`Duplicate base form with differing type: ${base} (${seen.get(base)} vs ${type})`);
    }
    seen.set(base, type);
    entries.push([base, type]);
  }

  const unique = [...seen.entries()];
  console.log(`Found ${entries.length} entries, ${unique.length} unique base forms.`);
  if (unique.length !== 109) {
    console.warn(`Expected 109 unique words, got ${unique.length}. The site's vocabulary may have changed — review before pasting.`);
  }

  const lines = unique
    .sort((a, b) => a[0].localeCompare(b[0], 'ja'))
    .map(([base, type]) => `  ${JSON.stringify(base)}: ${JSON.stringify(type)},`)
    .join('\n');

  const out = `// Auto-generated by tools/extract-words.js — see README.md to regenerate.
// Maps a word's base form (furigana stripped) to the site's word-class code:
//   u = う-verb, ru = る-verb, irv = irregular verb,
//   i = い-adjective, na = な-adjective, ira = irregular adjective
globalThis.JCS = globalThis.JCS || {};
JCS.WORD_CLASS = {
${lines}
};
`;
  console.log(out);
})();
